
        // Generated by sketch-assistant-generator

          const CoreAssistant = require('@sketch-hq/sketch-core-assistant');
          export const extendedAssistants = [CoreAssistant];
          export const rules = {"@sketch-hq/sketch-core-assistant/artboards-grid":{"active":true,"grids":[{"gridBlockSize":5,"thickLinesEvery":10},{"gridBlockSize":10,"thickLinesEvery":20}]},"@sketch-hq/sketch-core-assistant/result-messages-include":{"ruleTitle":"Page names should start with a 🍆","active":true,"message":"console.log('asd')"}};
        