export const TEMPLATE_DIR = 'files/assistant-template';
export const PACKAGE_JSON = {
  name: 'sketch-assistant',
  homepage: 'https://github.com/kharboush/sketch-assistant',
  version: '1.0.0',
  main: 'dist/index.js',
  sketch: 'dist/sketch.js',
  license: 'MIT',
  'sketch-assistant': {
    title: 'Sketch Modular Assistant',
    description: 'Watch this space',
    icon: '',
  },
  author: {
    name: 'Your Name or Company Name',
  },
  keywords: [
    'sketch',
    'sketch files',
    'sketch assistant',
    'public',
    'assistant',
    'design ops',
  ],
  files: ['dist'],
  scripts: {
    test: 'jest --no-cache',
    build: 'rm -rf dist && npm run build:node && npm run build:sketch',
    'build:node': 'tsc',
    'build:sketch': 'webpack',
    'package-tarball': 'npm run build && npm run pack',
    pack: '(cd output/ && exec npm pack ../)',
  },
  devDependencies: {
    '@sketch-hq/sketch-assistant-utils': '6.0.0',
    '@sketch-hq/sketch-assistant-types': '6.0.0',
    '@sketch-hq/sketch-core-assistant': '^6.1.0',
    '@types/jest': '26.0.4',
    '@types/node': '14.0.22',
    eslint: '^7.7.0',
    jest: '26.1.0',
    'node-fetch': '2.6.0',
    prettier: '2.0.5',
    'ts-jest': '26.1.2',
    typescript: '3.9.6',
    webpack: '4.43.0',
    'webpack-cli': '3.3.12',
  },
  dependencies: {},
};
